Repository thoth-station/revsolver, pull requests merged in 2020-07, with the labels that each got.

#3 Remove OpenShift template, they are part of thoth-application
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/L

#4 Fix environment variable name
  app.py
Labels: approved, size/XS

#5 Automatic update of dependency thoth-common from 0.12.9 to 0.14.1
  Pipfile.lock
Labels: approved, bot, size/L

#6 Automatic update of dependency thoth-storages from 0.22.7 to 0.24.0
  Pipfile.lock
Labels: approved, bot, size/L

#7 Automatic update of dependency click from 7.1.1 to 7.1.2
  Pipfile.lock
Labels: approved, bot, size/L

#8 Automatic update of dependency thoth-python from 0.9.2 to 0.10.0
  Pipfile.lock
Labels: approved, bot, size/L

#11 Automatic update of dependency thoth-storages from 0.24.0 to 0.24.2
  Pipfile.lock
Labels: approved, bot, size/S

#12 Adjust version string so that it works with Kebechet
  app.py
Labels: approved, size/XS

#14 Release of version 0.2.0
  CHANGELOG.md
  app.py
Labels: approved, bot, size/S

#15 Parsing of solver name has been moved to OpenShift class
  app.py
Labels: approved, size/XS

#16 Query count is an integer
  app.py
Labels: approved, size/XS

#18 Release of version 0.2.1
  CHANGELOG.md
  app.py
Labels: approved, bot, size/XS

#19 enable pre-commit support for the application
  .coafile
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  .pre-commit-config.yaml
  .zuul.yaml
  app.py
Labels: approved, size/L

#20 Automatic update of dependency thoth-storages from 0.24.2 to 0.24.3
  Pipfile.lock
Labels: approved, bot
