Repository thoth-station/revsolver, pull requests merged in 2020-11, with the labels that each got.

#35 port to python 38
  Pipfile
  Pipfile.lock
Labels: approved, size/XL

#36 update .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#38 update aicoe-ci configuration for revsolver
  .aicoe-ci.yaml
Labels: approved, size/S

#40 set back v0.20.1
  .aicoe-ci.yaml
Labels: approved, size/XS
